#!/bin/sh

PREFIX="Loop unprocessed test files"
API=${API:-http://validator-api/api/v1}

while :
do
  DATASET=`curl -s $API/testqueue/next | python -c "import sys, json; ds = json.load(sys.stdin); print(ds['fileid'] + ' ' + ds['tmpworkspaceId'])"`

  set $DATASET

  FID=$1
  WSID=$2

  echo $FID
  echo $WSID
  
  if [ -z $FID ]; then
    echo "$PREFIX: Nothing found to process, waiting"
    sleep 1m
  
  else
    echo "$PREFIX: processing $MD5"
    ./webhook-scripts/inhouse-testfiles.sh $FID
    
    ./email-notification.sh $WSID
  fi  
done
