#!/bin/sh

PREFIX="Loop unprocessed files"
API=${API:-http://validator-api/api/v1}

while :
do
  DATASET=`curl -s $API/queue/next | python -c "import sys, json; ds = json.load(sys.stdin); print(ds['md5'])"`

  set $DATASET

  MD5=$1
  
  if [ -z $MD5 ]; then
    echo "$PREFIX: Nothing found to process, waiting"
    sleep 1m
  
  else
    echo "$PREFIX: processing $MD5"
    ./webhook-scripts/inhouse.sh $MD5  
  fi  
done