
# Site settings
title: IATI Data Validator
email: rolf@drostan.org
description: >
  Publicly available IATI validator with data quality feedback and tests
  for the guidelines of the Dutch Ministry of Foreign Affairs
